### ISSUE TITLE
低速网络下通话自动关闭

### ISSUE THREAD

**Issue by dingdongnigetou** [HackWebRTC/webrtc#14]
如题。

使用webrtc官方库做安卓p2p的通话，在网络上限速6KB/s，通信一段时间，大约10几秒后通话就自动关闭了，猜测是因为丢包率太大引起的，丢包率大约是10%左右。

想问下大佬webrtc底层有这个限制么，有点坑，这个速率其实是可以正常通话的

**Comment by Piasy** [comment]
也许可以，也许不行，你可以深入研究研究

**Comment by dingdongnigetou** [comment]
打了底层日志发现是ping超时了，把超时时间跟尝试次数上调一下就好了:joy: 

大佬的书啥时候出版，来支持一下。

**Comment by Piasy** [comment]
八月份吧

**Comment by dingdongnigetou** [comment]
大佬请教一下，当安卓的网络有变化时，通话链接会断掉，有什么办法可以重连么。 

我看webrtc支持所谓的IceRestart，但是不管用啊在安卓。

还有一个机制是MICE，但是webrtc没实现。

最笨的只能重头走一遍协议重连了。
