### ISSUE TITLE
关于iOS demo的生成？

### ISSUE THREAD

**Issue by xuandu** [HackWebRTC/webrtc#17]
您好，按照您书上说的，因为公司网络限制原因并不能下载源码；我通过镜像下咋的编了几次也编不过，可能中途下载的东西还有些问题；所以想问问如果我只下载depot_tools，和您现在github上的这个webrtc，能不能编译出iOSdemo啊？具体需要怎么实现呢？

**Comment by Piasy** [comment]
不能，必须按照书中的步骤完整操作（sync）。
