### ISSUE TITLE
Facing issue when try to build

### ISSUE THREAD

**Issue by csguys** [HackWebRTC/webrtc#18]
After running below command

`gn gen out/Debug --args='target_os="android" target_cpu="arm"'
`
get below error

```
gn.py: Could not find checkout in any parent of the current path.
This must be run inside a checkout.

```

**Comment by Piasy** [comment]
As the error message said, you should sync code and run command as described in WebRTC's doc.

**Comment by csguys** [comment]
@Piasy when i try to run 
`gclient sync`

this happens 

`Error: client not configured; see 'gclient config'`
