### ISSUE TITLE
最新macOS 系统编译报错，macOS10.15

### ISSUE THREAD

**Issue by comlog** [HackWebRTC/webrtc#22]
ERROR at //BUILD.gn:374:12: Unsupported value in libs.
  libs = [ "Foundation.framework" ]
           ^---------------------
Use frameworks to list framework dependencies.

**Comment by ShikinChen** [comment]
我也出现这个问题 新版m90分支好像就没这个问题 但是代码无法在android studio编译

**Comment by Piasy** [comment]
后面我会再更新一波，rebase 到到时最新的版本上，不过可能得等一段时间。

**Comment by comlog** [comment]
webrtc  可以在QT  上面 使用吗？

**Comment by Piasy** [comment]
应该是可以的

**Comment by comlog** [comment]
> 应该是可以的

大神 有做过吗？我现在要在macOS 应用，然后用QT 来开发
