### ISSUE TITLE
你好，想问一下webrtc本地回环是怎么实现的？

### ISSUE THREAD

**Issue by xuandu** [HackWebRTC/webrtc#28]
我照着您书上的代码块，写了一个简单地1v1,demo; ios ;socketrocket 连接信令服务器ws进行message type的转发；想问问您本地回环是怎么做的；我现在自己发offer给自己，然后遇到answer就不处理（我看官方demo里有注释说本地回环不处理answer）；其他的也没变；可是我发现 offer ，setlocalsdp candidate，等也有网络传输；message.type::: candidate, 
 body: {"session_id":"L3Lv5eLF4XGZ-L3Lv5eLF4XGZ","to":"L3Lv5eLF4XGZ","candidate":{"sdpMLineIndex":0,"candidate":"candidate:1078800203 1 tcp 1518149375 169.254.81.159 54571 typ host tcptype passive generation 0 ufrag mF+B network-id 3 network-cost 10","sdpMid":"audio"},"type":"candidate"}
也已经触发了远端媒体流的接收：
vc.onAddStream = ^(PeerConnection *_Nonnull connect, RTCPeerConnection *_Nonnull peerConnection, RTCMediaStream *_Nonnull stream) {
       
        PeerConnection *pc = connect;
        dispatch_async(dispatch_get_main_queue(), ^{
            __strong CallVC *strongSelf = weakSelf;
            if (stream.videoTracks.count > 0 && pc != NULL) {
                RTCVideoTrack *remoteVideoTrack = stream.videoTracks[0];
                RTCEAGLVideoView *remoteView = strongSelf.remoteView;
                [remoteVideoTrack addRenderer:remoteView];
                pc.videoTrack = remoteVideoTrack;
            }
        });
    };

这是本地打印：
didReceiveMessage{"type":"candidate","data":{"from":"L3Lv5F4XGZ","to":"L3Lv5F4XGZ","candidate":{"sdpMLineIndex":0,"candidate":"candidate:1078800203 1 tcp 1518149375 169.254.81.159 54571 typ host tcptype passive generation 0 ufrag mF+B network-id 3 network-cost 10","sdpMid":"audio"}}}

但是就是没有音视频的播放；由于我使用的是iOS pod 直接安装的webrtc，所以无法断点调试；想问下，您这个loopback是怎是实现的，有哪些注意点

谢谢

**Comment by Piasy** [comment]
create offer，拿到 sdp 后，set remote sdp 设置进去。安卓官方 demo 就有 loopback 功能。
