### ISSUE TITLE
WebRTC h264 硬體編碼

### ISSUE THREAD

**Issue by lui-shex** [HackWebRTC/webrtc#30]
您好，我買了WebRTC Navtive實戰這本書，在書上，看到有關視頻數據流和支援H264的教學，想請問有辦法用硬體編碼(像ffmpeg h264_nvenc)去編碼webRTC上傳到h264_encode_imp(open_h264)的VideoFrameㄇ?
謝謝!

作業系統 : Ubuntu 20.04

**Comment by Piasy** [comment]
你这个需求肯定是需要去修改 webrtc 的代码了，或者通过自定义 encoder factory，创建基于 ffmpeg、支持硬编的 encoder。

**Comment by lui-shex** [comment]
我修改了，h264_encode_impl，套入ffmpeg codec，但我不知道如何link ffmpeg libavcodec.so, libavutil.so那些相關的libs，請問有什麼相關的教學嗎?
謝謝!

**Comment by Piasy** [comment]
这个周末我整理一篇 blog 吧。

**Comment by lui-shex** [comment]
非常感謝!
如果您整理好了，麻煩通知我一下，謝謝!

**Comment by Piasy** [comment]
先给你简单说下吧，我这边编译环境还在恢复中……

```bash
# 首先把 webrtc 项目里的 clang 路径添加到 PATH 环境变量中
export PATH=<webrtc checkout root>/src/third_party/llvm-build/Release+Asserts/bin:$PATH

# 然后 cd 到 src/third_party/ffmpeg，执行下面三个命令
python chromium/scripts/build_ffmpeg.py linux x64 --branding Chrome -- --enable-parser=hevc --enable-demuxer=mpegts --enable-protocol=file --enable-muxer=matroska
./chromium/scripts/copy_config.sh
./chromium/scripts/generate_gn.py
```

上面三个命令，第一个命令是使用自定义的 ffmpeg 编译参数，对 ffmpeg 进行尝试编译，自定义参数为 `--enable-parser=hevc --enable-demuxer=mpegts --enable-protocol=file --enable-muxer=matroska`，你可按需替换为你实际需要的参数；后两个命令是把刚才编译的参数、gn 配置，应用到 webrtc 项目中，这样用 ninja 命令编译的时候，就可以使用你自定义的参数了。

至于 link ffmpeg 的库，你就在 BUILD.gn 相关的 target 的 deps 里添加 `//third_party/ffmpeg` 即可。

**Comment by lui-shex** [comment]
由於之後要串接WebRTC流程，想說走conductor.cc -> webrtc::CreatePeerConnectionFactory ，替換掉 webrtc::CreateBuiltinVideoEncoderFactory，改成Nvidia video codec 支援硬體編碼的版本，後續串接流程就不需更改，有參考了下方的github，但由於他是基於window directX的版本，想改成linux 吃的 cuda版本。

但不太懂NvEncodeCuda 運作流程，對照著NvEncodeD3D11一頓瞎改，結果畫面都是空的......，想請問您對這邊有研究過嗎。

(最下方連結是一些我修改過的程式碼)

https://github.com/PHZ76/webrtc-native-demo
https://drive.google.com/file/d/1O-2M5nTAxU4fbqY8PxpO7FiL7g64wPSV/view?usp=sharing

**Comment by Piasy** [comment]
哈，后面具体的工作就得你自己搞定了哇。不过若你有预算，我可提供咨询服务，具体可以邮件沟通，xz4215@gmail.com。
