### ISSUE TITLE
请问下 android下如何使用ndk 用源码开发呢

### ISSUE THREAD

**Issue by chenzhu005774** [HackWebRTC/webrtc#36]
请问下 android下如何使用ndk 用源码开发呢

**Comment by Piasy** [comment]
可以参考下 https://blog.piasy.com/2018/08/14/build-webrtc/index.html
，但应该需要根据最新项目设置，做一些修改适配

Best regards.
Piasy Xu

此致，祝好！
许建林

<https://github.com/Piasy>

<https://www.linkedin.com/in/piasy>

**Comment by chenzhu005774** [comment]
感谢您的回复，我尝试下载过此项目 但由于能力有限 能否 发布一个完整的项目呢 谢谢

**Comment by chenzhu005774** [comment]
我看到下面您有知识星球 我加您知识了。知识还是应该付费获取
