### ISSUE TITLE
Android如何编译

### ISSUE THREAD

**Issue by why077** [HackWebRTC/webrtc#37]
请问代码下载后本地如何编译出peerconnectionxxx.so文件?

**Comment by Piasy** [comment]
看 webrtc 的官方说明文档，或者，买一本《WebRTC Native 开发实战》

**Comment by why077** [comment]
您好,我这边已经买过了《WebRTC Native 开发实战》这本书,但是对于伴奏那边不太明白,已经根据书的内容把伴奏相关的数据复制到webrtc源码中,但是编译似乎没有走这边;用的全部编译,编译产物不包括伴奏
想问下,您的github上的代码直接复制到webrtc源码里替换相应文件后可以直接编译么?这边iOS试过是可以的但是Android一直报错,类似下面这个报错,不太明白如何解决

ERROR Unresolved dependencies.
//media:rtc_audio_video(//build/toolchain/android:android_clang_arm)
  needs //rtc_base/experiments:experimental_screenshare_settings(//build/toolchain/android:android_clang_arm)
//modules/video_coding:video_coding(//build/toolchain/android:android_clang_arm)
  needs //api/video:video_adaptation(//build/toolchain/android:android_clang_arm)
//modules/video_coding:video_coding_utility(//build/toolchain/android:android_clang_arm)
  needs //api/video:video_adaptation(//build/toolchain/android:android_clang_arm)
//video:video_stream_encoder_impl(//build/toolchain/android:android_clang_arm)
  needs //api/video:video_adaptation(//build/toolchain/android:android_clang_arm)
//video/adaptation:video_adaptation(//build/toolchain/android:android_clang_arm)
  needs //api/video:video_adaptation(//build/toolchain/android:android_clang_arm)


Traceback (most recent call last):
  File "./tools_webrtc/android/build_aar.py", line 234, in <module>
    sys.exit(main())
  File "./tools_webrtc/android/build_aar.py", line 230, in main
    args.build_dir, args.extra_gn_switches, args.extra_ninja_switches)
  File "./tools_webrtc/android/build_aar.py", line 210, in BuildAar
    extra_ninja_switches)
  File "./tools_webrtc/android/build_aar.py", line 166, in Build
    _RunGN(gn_args_list)
  File "./tools_webrtc/android/build_aar.py", line 93, in _RunGN
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '/root/webrtc/src/third_party/depot_tools/gn.py', 'gen', '/tmp/tmps0s1jo/armeabi-v7a', '--args=arm_version=7 use_goma=false target_cpu="arm" is_component_build=false is_debug=false rtc_include_tests=false target_os="android"']' returned non-zero exit status 1













在 2023-01-20 15:05:42，"Piasy" ***@***.***> 写道：

看 webrtc 的官方说明文档，或者，买一本《WebRTC Native 开发实战》

**Comment by Piasy** [comment]
还需要修改 webrtc 项目配置文件的，可以看看这里的提交内容

**Comment by why077** [comment]
老师您好,目前我是根据书4.4的步骤来加的,根据书的内容改了modules/BULD.gn和android/sdk/BUILD.gn,然后再把相关内容复制到指定位置,但是编译失败;想问下老师还需要改其他位置的代码么?书里的内容是不全的么











在 2023-02-10 09:02:58，"Piasy" ***@***.***> 写道：

还需要修改 webrtc 项目配置文件的，可以看看这里的提交内容

**Comment by why077** [comment]
我源码下载31262-M84分支,然后把你30987分支代码覆盖到源码在编译的
还有就是编译后会报:
FAILED: gen/api/video/video_frame_enums.srcjar







在 2023-02-10 09:02:58，"Piasy" ***@***.***> 写道：

还需要修改 webrtc 项目配置文件的，可以看看这里的提交内容

**Comment by Piasy** [comment]
完整代码以这个仓库的提交为准，另外如果你基于的 webrtc 版本不一样，那可能也需要做一些调整。

**Comment by why077** [comment]
不好意思打扰了;


我在知识星球里也问了,您说准备好webrtc编译环境(已经准备好Ubuntu/Linux环境),在获取指定分支代码,也已经下载并上传到Ubuntu指定位置

第一步:我先把您仓库代码上传到Ubuntu/Linux环境指定位置
第二步,我gclient sync
问题是,我gclient sync后,仓库代码就变了,里面会删除您写的混音部分,
现在想问下,我的步骤是不是有问题











在 2023-02-10 22:01:08，"Piasy" ***@***.***> 写道：

完整代码以这个仓库的提交为准，另外如果你基于的 webrtc 版本不一样，那可能也需要做一些调整。

**Comment by Piasy** [comment]
sync 不会改主仓代码的，只是会把 third_party 依赖切换到对应的提交。最简单的办法，比如你找到 peer_connection.cc，在里面改几行代码，你再重新 sync 一遍，看看你的改动是否还在。
伴奏相关的代码修改，都是在主仓里。

**Comment by why077** [comment]
您好,最近您忙么?可以微信联系到您么?花费您一点时间,如果可以费用方面您也可以提下
混音已经卡了很久了,麻烦您帮忙看下可以么?我的微信13914721187
或者您可以把微信联系方式发我







在 2023-02-12 13:49:23，"Piasy" ***@***.***> 写道：

sync 不会改主仓代码的，只是会把 third_party 依赖切换到对应的提交。最简单的办法，比如你找到 peer_connection.cc，在里面改几行代码，你再重新 sync 一遍，看看你的改动是否还在。
伴奏相关的代码修改，都是在主仓里。

**Comment by why077** [comment]
我第一步是 fetch --nohooks webrtc_android 然后再切到30987分支去,但是这个切过去的代码是不包括混音的,根据书内容也编译不出来

还是说我直接把您仓库代码复制到环境上去,然后直接gclient sync,再编译?这会有个问题,就是我把代码复制后sync后会下载新的分支内容,我之前的代码回去_bad_xxx目录里,主代码里就会丢失bracking_track代码

老师您最近很忙么?能否加您微信具体问下您细节问题,这个问题困扰很久了,买了您的书和进入您的知识星球都没有解决,如果报酬方面可以说的; 这是我的微信13914721187
如果您不想加,可以和我说下大致步骤如何么
打扰您了,也求您抽空看下;十分抱歉







在 2023-02-12 13:49:23，"Piasy" ***@***.***> 写道：

sync 不会改主仓代码的，只是会把 third_party 依赖切换到对应的提交。最简单的办法，比如你找到 peer_connection.cc，在里面改几行代码，你再重新 sync 一遍，看看你的改动是否还在。
伴奏相关的代码修改，都是在主仓里。
