### ISSUE TITLE
How to use compile_native_code=true

### ISSUE THREAD

**Issue by HuuNguyen312** [HackWebRTC/webrtc#5]
Dear @Piasy ,

android_gradle is a great repository for exploring WebRTC Android in Android Studio.
I tried with use compile_native_code=false, it works very well.

I want to explore by using native code (compile_native_code=true). But I can't build.

This is the error log.

```
Error configuring CMake server (/Users/xxx/Library/Android/sdk/cmake/3.10.2.4988404/bin).

Check for working C compiler: /Users/xxx/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang

Check for working C compiler: /Users/xxx/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- works

Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
....

See also "/Users/xxx/HackWebrtc/sdk/android_gradle/webrtc/.externalNativeBuild/cmake/debug/x86/CMakeFiles/CMakeOutput.log".
```
Please help me resolve it.
Also, Can I build libjingle_peerconnection_so.so from Android Studio?

Thanks

**Comment by Piasy** [comment]
Did you read the README here? https://github.com/Piasy/webrtc/tree/hack_webrtc/sdk/android_gradle

I just build libjingle_peerconnection_so.so within Android Studio and debug C++ code (break point and step in) successfully before I push the latest commit.

**Comment by HuuNguyen312** [comment]
Thanks for your responding.

I have read the README 

1. you need download and sync WebRTC repo by yourself, this project won't do that for you;
2. use the same version of Android SDK and NDK as WebRTC does;
3. (re)create protoc after updating webrtc repo, build WebRTC with ninja would create it;
4. delete webrtc_build_dir after updating webrtc repo;

Please help us explain step 3.

My gradle.properties
/Users/huunn/GitHub/WebRTC/webrtc-checkout/ is my WebRTC checkout location from https://webrtc.org/native-code/android/

```
webrtc_repo=/Users/huunn/GitHub/WebRTC/webrtc-checkout/src
webrtc_build_dir=out/android_studio

android_jar=third_party/android_tools_mac/sdk/platforms/android-28/android.jar

py2=/Users/piasy/anaconda3/envs/py2/bin/python
protoc=/Users/huunn/GitHub/WebRTC/webrtc-checkout/src
```

When Android Studio build,  it return the error 

```Build command failed.
Error while executing process /Users/huunn/Library/Android/sdk/cmake/3.10.2.4988404/bin/cmake with arguments {--build /Users/huunn/GitHub/WebRTC/webrtc-checkout/src/sdk/android_gradle/webrtc/.externalNativeBuild/cmake/debug/x86 --target jingle_peerconnection_so}
[1/1861] Generating err_data.c
FAILED: third_party/boringssl/boringssl/crypto/err_data.c 
cd /Users/huunn/GitHub/WebRTC/webrtc-checkout/src/third_party/boringssl/src/crypto/err && go run err_data_generate.go > /Users/huunn/GitHub/WebRTC/webrtc-checkout/src/sdk/android_gradle/webrtc/.externalNativeBuild/cmake/debug/x86/third_party/boringssl/boringssl/crypto/err_data.c
/bin/sh: go: command not found
[2/1861] Generating chacha/chacha-x86.S
[3/1861] Linking C static library third_party/libsrtp/libsrtp.a
[4/1861] Linking CXX static library third_party/abseil-cpp/abseil-cpp/absl/strings/libabsl_strings.a
[5/1861] Building C object third_party/libvpx/CMakeFiles/vpx.dir/Users/huunn/GitHub/WebRTC/webrtc-checkout/src/third_party/libvpx/source/libvpx/vp8/common/arm/neon/idct_dequant_full_2x_neon.c.o
FAILED: third_party/libvpx/CMakeFiles/vpx.dir/Users/huunn/GitHub/WebRTC/webrtc-checkout/src/third_party/libvpx/source/libvpx/vp8/common/arm/neon/idct_dequant_full_2x_neon.c.o 
/Users/huunn/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang --target=i686-none-linux-android16 --gcc-toolchain=/Users/huunn/Library/Android/sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/huunn/Library/Android/sdk/ndk-bundle/sysroot  -I/Users/huunn/GitHub/WebRTC/webrtc-checkout/src/third_party/libvpx/source/config -I/Users/huunn/GitHub/WebRTC/webrtc-checkout/src/third_party/libvpx/source/config/linux/arm64 -I/Users/huunn/GitHub/WebRTC/webrtc-checkout/src/third_party/libvpx/source/libvpx -isystem /Users/huunn/Library/Android/sdk/ndk-bundle/sysroot/usr/include/i686-linux-android -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mstackrealign -Wa,--noexecstack -Wformat -Werror=format-security  -O0 -fno-limit-debug-info  -fPIC -MD -MT third_party/libvpx/CMakeFiles/vpx.dir/Users/huunn/GitHub/WebRTC/webrtc-checkout/src/third_party/libvpx/source/libvpx/vp8/common/arm/neon/idct_dequant_full_2x_neon.c.o -MF third_party/libvpx/CMakeFiles/vpx.dir/Users/huunn/GitHub/WebRTC/webrtc-checkout/src/third_party/libvpx/source/libvpx/vp8/common/arm/neon/idct_dequant_full_2x_neon.c.o.d -o third_party/libvpx/CMakeFiles/vpx.dir/Users/huunn/GitHub/WebRTC/webrtc-checkout/src/third_party/libvpx/source/libvpx/vp8/common/arm/neon/idct_dequant_full_2x_neon.c.o   -c /Users/huunn/GitHub/WebRTC/webrtc-checkout/src/third_party/libvpx/source/libvpx/vp8/common/arm/neon/idct_dequant_full_2x_neon.c
In file included from /Users/huunn/GitHub/WebRTC/webrtc-checkout/src/third_party/libvpx/source/libvpx/vp8/common/arm/neon/idct_dequant_full_2x_neon.c:11:
/Users/huunn/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/7.0.2/include/arm_neon.h:28:2: error: "NEON support not enabled"
#error "NEON support not enabled"
```
Thanks

**Comment by Piasy** [comment]
I've pushed a [new commit](https://github.com/Piasy/webrtc/commit/fb6f6797d87a0556faf51ba2d35e828e6f3731fd), please check the diff.

**Comment by ducanh3005** [comment]
> Thanks for your responding.
> 
> I have read the README
> 
> 1. you need download and sync WebRTC repo by yourself, this project won't do that for you;
> 2. use the same version of Android SDK and NDK as WebRTC does;
> 3. (re)create protoc after updating webrtc repo, build WebRTC with ninja would create it;
> 4. delete webrtc_build_dir after updating webrtc repo;
> 
> Please help us explain step 3.
> 
> My gradle.properties
> /Users/huunn/GitHub/WebRTC/webrtc-checkout/ is my WebRTC checkout location from https://webrtc.org/native-code/android/
> 
> ```
> webrtc_repo=/Users/huunn/GitHub/WebRTC/webrtc-checkout/src
> webrtc_build_dir=out/android_studio
> 
> android_jar=third_party/android_tools_mac/sdk/platforms/android-28/android.jar
> 
> py2=/Users/piasy/anaconda3/envs/py2/bin/python
> protoc=/Users/huunn/GitHub/WebRTC/webrtc-checkout/src
> ```
> 
> When Android Studio build, it return the error
> 
> ```
> Error while executing process /Users/huunn/Library/Android/sdk/cmake/3.10.2.4988404/bin/cmake with arguments {--build /Users/huunn/GitHub/WebRTC/webrtc-checkout/src/sdk/android_gradle/webrtc/.externalNativeBuild/cmake/debug/x86 --target jingle_peerconnection_so}
> [1/1861] Generating err_data.c
> FAILED: third_party/boringssl/boringssl/crypto/err_data.c 
> cd /Users/huunn/GitHub/WebRTC/webrtc-checkout/src/third_party/boringssl/src/crypto/err && go run err_data_generate.go > /Users/huunn/GitHub/WebRTC/webrtc-checkout/src/sdk/android_gradle/webrtc/.externalNativeBuild/cmake/debug/x86/third_party/boringssl/boringssl/crypto/err_data.c
> /bin/sh: go: command not found
> [2/1861] Generating chacha/chacha-x86.S
> [3/1861] Linking C static library third_party/libsrtp/libsrtp.a
> [4/1861] Linking CXX static library third_party/abseil-cpp/abseil-cpp/absl/strings/libabsl_strings.a
> [5/1861] Building C object third_party/libvpx/CMakeFiles/vpx.dir/Users/huunn/GitHub/WebRTC/webrtc-checkout/src/third_party/libvpx/source/libvpx/vp8/common/arm/neon/idct_dequant_full_2x_neon.c.o
> FAILED: third_party/libvpx/CMakeFiles/vpx.dir/Users/huunn/GitHub/WebRTC/webrtc-checkout/src/third_party/libvpx/source/libvpx/vp8/common/arm/neon/idct_dequant_full_2x_neon.c.o 
> /Users/huunn/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang --target=i686-none-linux-android16 --gcc-toolchain=/Users/huunn/Library/Android/sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/huunn/Library/Android/sdk/ndk-bundle/sysroot  -I/Users/huunn/GitHub/WebRTC/webrtc-checkout/src/third_party/libvpx/source/config -I/Users/huunn/GitHub/WebRTC/webrtc-checkout/src/third_party/libvpx/source/config/linux/arm64 -I/Users/huunn/GitHub/WebRTC/webrtc-checkout/src/third_party/libvpx/source/libvpx -isystem /Users/huunn/Library/Android/sdk/ndk-bundle/sysroot/usr/include/i686-linux-android -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mstackrealign -Wa,--noexecstack -Wformat -Werror=format-security  -O0 -fno-limit-debug-info  -fPIC -MD -MT third_party/libvpx/CMakeFiles/vpx.dir/Users/huunn/GitHub/WebRTC/webrtc-checkout/src/third_party/libvpx/source/libvpx/vp8/common/arm/neon/idct_dequant_full_2x_neon.c.o -MF third_party/libvpx/CMakeFiles/vpx.dir/Users/huunn/GitHub/WebRTC/webrtc-checkout/src/third_party/libvpx/source/libvpx/vp8/common/arm/neon/idct_dequant_full_2x_neon.c.o.d -o third_party/libvpx/CMakeFiles/vpx.dir/Users/huunn/GitHub/WebRTC/webrtc-checkout/src/third_party/libvpx/source/libvpx/vp8/common/arm/neon/idct_dequant_full_2x_neon.c.o   -c /Users/huunn/GitHub/WebRTC/webrtc-checkout/src/third_party/libvpx/source/libvpx/vp8/common/arm/neon/idct_dequant_full_2x_neon.c
> In file included from /Users/huunn/GitHub/WebRTC/webrtc-checkout/src/third_party/libvpx/source/libvpx/vp8/common/arm/neon/idct_dequant_full_2x_neon.c:11:
> /Users/huunn/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/7.0.2/include/arm_neon.h:28:2: error: "NEON support not enabled"
> #error "NEON support not enabled"
> ```
> 
> Thanks

Can you help me to build this project
