### ISSUE TITLE
libwebrtc.a总是无法链接到ffmpeg对应的方法

### ISSUE THREAD

**Issue by hbblzjy** [HackWebRTC/webrtc#52]
添加了本地录制模块，生成的静态库在demo中运行总是报错显示：
error build: Undefined symbol: _av_strerror
error build: Undefined symbol: _avformat_alloc_output_context2
error build: Undefined symbol: _avformat_free_context
error build: Undefined symbol: _avio_open
大佬，想问问是什么原因，怎么能够链接到ffmpeg，我已经在sdk文件夹下添加了libs文件夹，而且添加了recording文件夹

**Comment by Piasy** [comment]
回复得有点晚了 😅
这种情况要么就是你没有把 ffmpeg 的库实际链接进去，要么就是虽然链接了，但是编译的 ffmpeg 代码不全，没有包含上面报错的那些符号。
另外 https://blog.piasy.com/2021/06/21/Hack-WebRTC-32599/index.html 这边文章也有在 webrtc 代码库里面，集成 ffmpeg 相关的说明，可以参考下。
