### ISSUE TITLE
VideoFileRenderer

### ISSUE THREAD

**Issue by KingArmstring** [HackWebRTC/webrtc#7]
I used the same implementation of the VideoFileRenderer you made, it worked but I am having the following issues:

1. I have recorded a 3 seconds video file, its size is about 40 MegaBytes, is that normal, I tried to change the resolution of video captured so that its quality gets reduced, but this did not make any difference.
2. I could not play the video except with external apps like MXPlayer (could not play it with the normal video player that comes embedded with the android) I wrote about that I found that it is of extension .y4m, I tried to convert it programmatically into mp4 or something playable by the native VideoView or even the video player that comes with the android but could not.
3. This is not an issue: how to do the same with audio, i.e. what is the VideoFileRenderer for audio

I really appreciate your effort in webrtc, Thanks in advance.

**Comment by Piasy** [comment]
At first, I didn't commit any actual code into this repo, all the source code commit history are the same with the official repo, the real content of this repo is the `sdk/android_gradle` folder, which is a collection of build scripts. Although I contribute several patches into the official webrtc repo :)

Regarding your questions: if you read VideoFileRenderer's source code, you will find answers of your questions :)
