### ISSUE TITLE
h264的支持

### ISSUE THREAD

**Issue by zengpeace** [HackWebRTC/webrtc#8]
清华大虾你好，原版app好像只支持vp8 vp9，但是c++代码里面有不少h264的代码，gn gen的参数也有h264的部分，但是对于安卓跟ios好像默认不使能的，我试了下强行使能它，但是在app里面使用h264编码，出来的结果还是vp8。不知道你对这方面有没有了解？欢迎交流，如果能直接兼容好h264，那就更好了。

**Comment by Piasy** [comment]
WebRTC 原生支持 H.264 硬编硬解。
